# Generated by Django 4.0.2 on 2022-03-08 01:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tailors",
            name="pictures",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(
                    blank=True, null=True, upload_to="tailor-pictures"
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="displayPicture",
            field=models.ImageField(null=True, upload_to="user-images"),
        ),
    ]
