# Generated by Django 4.0.2 on 2022-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('charges', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(default=0)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('status', models.CharField(default='requested', max_length=255)),
                ('client_address', models.CharField(blank=True, max_length=255, null=True)),
                ('client_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
