# Generated by Django 4.0.2 on 2022-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
